<font color=blue>__Třídění a výběr záznamů__</font>

In [1]:
import pandas as pd

<font color=red>parametr usecols</font>

In [2]:
# parametr 'usecols' umožní výběr jednotlivých sloupců
imdb = pd.read_csv('../data/imdb_1000.csv', usecols = ['star_rating','title','content_rating','genre','duration'])

In [3]:
imdb.head()

   star_rating                     title content_rating   genre  duration
0          9.3  The Shawshank Redemption              R   Crime       142
1          9.2             The Godfather              R   Crime       175
2          9.1    The Godfather: Part II              R   Crime       200
3          9.0           The Dark Knight          PG-13  Action       152
4          8.9              Pulp Fiction              R   Crime       154

<font color=red>metoda sort_values - Series</font>

In [4]:
# sort_values - třídění (pandas Series) sloupce podle abecedy (vzestupně)
imdb.title.sort_values().head()

542     (500) Days of Summer
5               12 Angry Men
201         12 Years a Slave
698                127 Hours
110    2001: A Space Odyssey
Name: title, dtype: object

In [5]:
# sort_values - třídění sloupce podle abecedy (sestupně -> ascending = False)
imdb.title.sort_values(ascending = False).head()

864               [Rec]
526                Zulu
615          Zombieland
677              Zodiac
955    Zero Dark Thirty
Name: title, dtype: object

<font color=red>metoda sort_values - DataFrame</font>

In [6]:
imdb.sort_values('title').head()

     star_rating                  title content_rating      genre  duration
542          7.8   (500) Days of Summer          PG-13     Comedy        95
5            8.9           12 Angry Men      NOT RATED      Drama        96
201          8.1       12 Years a Slave              R  Biography       134
698          7.6              127 Hours              R  Adventure        94
110          8.3  2001: A Space Odyssey              G    Mystery       160

<font color=red>metoda sort_values - DataFrame (třídění podle několika sloupců)</font>

In [8]:
imdb.sort_values(['title','duration'], ascending=False).head()

     star_rating             title content_rating   genre  duration
864          7.5             [Rec]              R  Horror        78
526          7.8              Zulu        UNRATED   Drama       138
615          7.7        Zombieland              R  Comedy        88
677          7.7            Zodiac              R   Crime       157
955          7.4  Zero Dark Thirty              R   Drama       157

In [10]:
imdb.sort_values(['genre','title']).head(20)

,star_rating,title,content_rating,genre,duration
570,7.8,300,R,Action,117
276,8.1,A Fistful of Dollars,R,Action,99
75,8.4,Aliens,R,Action,137
529,7.8,Apocalypto,R,Action,139
433,7.9,Avatar,PG-13,Action,162
801,7.6,Batman,PG-13,Action,126
113,8.3,Batman Begins,PG-13,Action,140
573,7.8,Battle Royale,NOT RATED,Action,114
82,8.4,Braveheart,R,Action,177
908,7.5,Bullitt,PG,Action,114
517,7.8,Captain America: The Winter Soldier,PG-13,Action,136
380,8.0,Casino Royale,PG-13,Action,144
437,7.9,"Crouching Tiger, Hidden Dragon",PG-13,Action,120
623,7.7,Dawn of the Planet of the Apes,PG-13,Action,130
138,8.3,Die Hard,R,Action,131
778,7.6,Die Hard: With a Vengeance,R,Action,131
515,7.8,Dirty Harry,R,Action,102
349,8.0,District 9,R,Action,112
391,8.0,Edge of Tomorrow,PG-13,Action,113
261,8.1,Elite Squad,R,Action,115

<font color=red>třídění pomocí logických operátorů 1 (podmínka pro výběr 'a', značí se znakem '&')</font>

In [19]:
# výběr záznamů, které mají hodnotu větší než ... a zároveň patří do ...
imdb[(imdb.star_rating >= 6.5) & (imdb.genre == 'Horror')].head(15)

,star_rating,title,content_rating,genre,duration
39,8.6,Psycho,R,Horror,109
57,8.5,Alien,R,Horror,117
62,8.5,The Shining,R,Horror,146
161,8.2,Diabolique,UNRATED,Horror,116
186,8.2,The Thing,R,Horror,109
317,8.0,Dawn of the Dead,UNRATED,Horror,127
322,8.0,The Exorcist,R,Horror,122
330,8.0,Nosferatu,UNRATED,Horror,81
351,8.0,Frankenstein,UNRATED,Horror,70
353,8.0,Night of the Living Dead,UNRATED,Horror,96
405,7.9,The Bride of Frankenstein,NOT RATED,Horror,75
513,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80
572,7.8,The Birds,PG-13,Horror,119
655,7.7,Saw,R,Horror,103
688,7.7,The Wicker Man,R,Horror,88

<font color=red>třídění pomocí logických operátorů  (podmínka pro výběr 'nebo', značí se znakem '|')</font>

In [22]:
# výběr záznamů, které patří do ... nebo do ... nebo do ... 
imdb[(imdb.genre == 'Action') | (imdb.genre == 'Drama') | (imdb.genre == 'Crime')].head(15)

,star_rating,title,content_rating,genre,duration
0,9.3,The Shawshank Redemption,R,Crime,142
1,9.2,The Godfather,R,Crime,175
2,9.1,The Godfather: Part II,R,Crime,200
3,9.0,The Dark Knight,PG-13,Action,152
4,8.9,Pulp Fiction,R,Crime,154
5,8.9,12 Angry Men,NOT RATED,Drama,96
9,8.9,Fight Club,R,Drama,139
11,8.8,Inception,PG-13,Action,148
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124
13,8.8,Forrest Gump,PG-13,Drama,142
16,8.7,One Flew Over the Cuckoo's Nest,R,Drama,133
17,8.7,Seven Samurai,UNRATED,Drama,207
19,8.7,Star Wars,PG,Action,121
20,8.7,The Matrix,R,Action,136
21,8.7,City of God,R,Crime,130

<font color=red>metoda isin() - jednodušší metoda pro výběr</font>

In [23]:
imdb[imdb.genre.isin(['Action','Drama','Crime'])].head(15)

,star_rating,title,content_rating,genre,duration
0,9.3,The Shawshank Redemption,R,Crime,142
1,9.2,The Godfather,R,Crime,175
2,9.1,The Godfather: Part II,R,Crime,200
3,9.0,The Dark Knight,PG-13,Action,152
4,8.9,Pulp Fiction,R,Crime,154
5,8.9,12 Angry Men,NOT RATED,Drama,96
9,8.9,Fight Club,R,Drama,139
11,8.8,Inception,PG-13,Action,148
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124
13,8.8,Forrest Gump,PG-13,Drama,142
16,8.7,One Flew Over the Cuckoo's Nest,R,Drama,133
17,8.7,Seven Samurai,UNRATED,Drama,207
19,8.7,Star Wars,PG,Action,121
20,8.7,The Matrix,R,Action,136
21,8.7,City of God,R,Crime,130